/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as tokenLauncherSol from "./TokenLauncher.sol";
export type { tokenLauncherSol };
export type { LaunchToken } from "./LaunchToken";
